### ISSUE TITLE
Enhancement - change delimiter @{} for js/jsdoc usage

### ISSUE THREAD

**Issue by StephaneTy-Pro** [CDSoft/ypp#1]
Hello,

I really love the ypp tool, i use it in differents projects in different languages
The problem is with jsdoc
i could include.raw chunks be not simply include them because jsdoc use @keywords{} in headers
a solution was to use @param\{} instead of @param{} but not practical
will it be possible to change the delimiter ?

**Comment by CDSoft** [comment]
Hi,

Thanks for the report.

It is currently not possible to change these delimiters.

There are several kinds of delimiters:

- `@` and `@@` are part of the ypp syntax and could be changed by adding a command line option or a macro to change the delimiter (this could be implemented easily)
- `{...}`, `(...)`, `[[...]]` are part of the Lua syntax and I would prefer not to change Lua itself ;-)

Would an option and a macro to change `@` and `@@` be enough?

e.g.:
``` sh
ypp -d "#" ...
```
or
```
@delim "#"
#myfunc{...}          <- equivalent to @myfunc{...} if @delim was not called
```

A short term woraround is to quote the text you don't want to process:
```
@q[[@param{...}]]         <- won't call param{...}
```
but I admit this is tedious in a file where `@` is part of the language.

**Comment by StephaneTy-Pro** [comment]
yes it would be perfect to change delim

usage of directive @delim "#" which switch the delimiter will be fantastic . It will introduce a question ... how children will be influenced by the directive (i prefer no influence xD)

Thanks for workaround

**Comment by CDSoft** [comment]
Very interesting question!

At first I thought it could affect whatever comes next (children and next documents) but it sounds safer to restrict the effect of this macro to the current file (and not its children). This way all files requiring a different configuration shall explicitly call `@delim`.

The same question arises for the command line option. Shall it be global or only for files on the command line (and not their children)? A way to answer this question would be not to have a command line option at all since the delimiter shall be associated to a file and it seems more natural to add it to the file itself (more explicit, less ambiguous).

**Comment by CDSoft** [comment]
I pushed a new version.

The `ypp` table has a method `ypp.macro` that changes the macro delimiter for the current file (it shall be a single character). E.g.:
```
@@ypp.macro "#"
=> from here expressions are #f(x) and statements are ##...
```

**Comment by StephaneTy-Pro** [comment]
it works like a charm

because i need that it was automatically included i have defined in the "inclusion" script (the script builder)

@@[===[ 
function import(s)
local z = '@ypp.macro("#")'
local z = z .. ypp.read_file(s)
return ypp(z)
end
]===]
@import('./src/test2.js')

or more shorter
@@[===[ 
function import(s)
ypp.macro("#")
return ypp(ypp.read_file(s))
end
]===]
@import('./src/test2.js')

the only question i have is .... will you keep this property accessible (read_file is not mentionned in doc as a builtin ypp functions)

**Comment by CDSoft** [comment]
I'll clean the ypp table (but keep and document `read_file`).

**Comment by CDSoft** [comment]
In version 1.0 (warning API breaking changes):

- the special syntax `?(...)` and `@/` are removed (`@q` and parentheses are preferred)
- special chars can be used for macros (e.g. : `?(...)`)
- `ypp.read_file` is documented

**Comment by StephaneTy-Pro** [comment]
houps i found a weird thing (but think it was normal) just wanna alert on this case
````
@@[===[
function import(s)
  ypp.macro("#")
  print"import"
  return "imp_1"
end

function import2()
  print "import2"
  return "imp_2"
end

]===]

@import("a")
@import("a")
@import2("a")
@import2("a")

````

first import ypp.macro() seem to break scope of function import or import2 
here as a result i see
import
nothing more

if i remove   ypp.macro("#") i could see

import
import
import2
import2

so i change macro import to include ypp.macro("@") before return => it works

**Comment by CDSoft** [comment]
This is "normal". `ypp.macro` changes the macro character for the rest of the input file (except for files included with the `include` function).

You will have to restore the previous character if you want the change to be local.

I can add a function to make it local to a portion of macro. e.g.:

``` lua
function foo()
    ypp.with_conf(function()
        ypp.macro "#"
        ...
    end)
    -- here the macro char is "@"
end
```

If fact this function already exists internally : 
``` lua
function foo()
    ypp.lconf(function()
        ypp.macro "#"
        ...
    end)
    -- here the macro char is "@"
end
```

`ypp.lconf` executes a function with a new local configuration that can be modified in the function and is dropped when the function exits.
This function is used by `include`.

Or a pair of functions to push a new configuration and pop it to restore the previous one:

```lua
function foo()
    ypp.push_conf()
    ypp.macro "#"
    ...
    ypp.pop_conf()
    -- here the macro char is "@"
end
```

But this can be dangerous since push and pop functions shall be correctly paired.

**Comment by StephaneTy-Pro** [comment]
thanks i'll use ypp.lconf
